---
facebook: &facebook
  app_id: 200605363362845
  secret_key: 1111111111111
  callback_url: http://apps.facebook.com/everyscheduler-dev/
  permissions: ""

development: *facebook

test: *facebook

production:
  <<: *facebook
  callback_url: http://apps.facebook.com/everyscheduler/
